name: Publish Package

on:
    push:
        tags:
            - "v*"

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Use Node.js 14.x
              uses: actions/setup-node@v2
              with:
                  node-version: "14.x"
                  registry-url: https://registry.npmjs.org/
            - name: publish
              run: |
                  cd ./eslint-config-ts/ && npm publish --access public && cd ..
                  cd ./eslint-config-vue/ && npm publish --access public && cd ..
                  cd ./eslint-config-basic/ && npm publish --access public && cd ..
                  cd ./eslint-config-react/ && npm publish --access public && cd ..
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
