name: Publish Package

on:
    push:
        tags:
            - "v*"

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Use Node.js 14.x
              uses: actions/setup-node@v2
              with:
                  scope: "@vecmat"
                  node-version: "14.x"
                  registry-url: https://registry.npmjs.org/
            - name: publish
              run: |
                  echo '${{ secrets.NPM_TOKEN }}' ;
                  cd ./eslint-config-ts/ ;
                  echo '//npmjs.com/:_authToken=${{ secrets.NPM_TOKEN }}' > .npmrc  ;
                  cat .npmrc ;
                  npm publish --access public && cd ..
                  cd ./eslint-config-vue/ ;
                  echo '//npmjs.com/:_authToken=${{ secrets.NPM_TOKEN }}' > .npmrc  ;
                  npm publish --access public && cd ..
                  cd ./eslint-config-basic/ ;
                  echo '//npmjs.com/:_authToken=${{ secrets.NPM_TOKEN }}' > .npmrc  ;
                  npm publish --access public && cd ..
                  cd ./eslint-config-react/ ;
                  echo '//npmjs.com/:_authToken=${{ secrets.NPM_TOKEN }}' > .npmrc  ;
                  npm publish --access public && cd ..
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
